#!/usr/bin/python3
import sys
import json
from colorama import Fore, Style, init
import helpers as h
init(autoreset=True)

PREVIOUS_HEAD = sys.argv[1]
NEW_HEAD = sys.argv[2]
IS_BRANCH_CHECKOUT = sys.argv[3]

# this is a file checkout, ignore.
if IS_BRANCH_CHECKOUT == "0": sys.exit(0)

# if we checkout to master or dev, ignore.
if h.get_current_branch() in ["master", "dev"]: sys.exit(0)

# if we checkout from dev, ensure we only checkout to allowed branches.
# ie a branch that corresponds to an issue key on JIRA.
if h.get_previous_branch() == "dev":
    ALLOWED_BRANCHES, DETAILS = h.call_jira()

    if h.get_current_branch() not in ALLOWED_BRANCHES:
        h.go_to_previous_branch_and_delete_current_branch()

        if ALLOWED_BRANCHES:
            print("""{0}

At the moment, the allowed branches are: {1}{2}{3}

For more details:
{4}""".format(
            Fore.RED + "You can only create branches based on JIRA issues/tickets." + Style.RESET_ALL,
            Fore.GREEN,
            ALLOWED_BRANCHES,
            Style.RESET_ALL,
            json.dumps(DETAILS, indent=4, sort_keys=True)
        ))
        else:
            print("""{0}You can only create branches based on JIRA issues/tickets.
You do not have any open JIRA issues/tickets.
""".format(Fore.RED))

        sys.exit(1)
    else:
        sys.exit(0)

h.go_to_previous_branch_and_delete_current_branch()
print("{0}You can only checkout to branch dev from master".format(Fore.YELLOW))
sys.exit(1)