#!/usr/bin/python3
import sys
import helpers as h
from colorama import Fore, Style, init
init(autoreset=True)

if h.get_current_branch() in ["Master", "dev"]:
    print(Fore.RED + "You cannot commit on *master* & and *dev* branches!")
    sys.exit(1)